# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFeedKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFeedKit

  target 'TestFeedKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestFeedKitUITests' do
    # Pods for testing
  end
  pod 'FeedKit'
end
